WorldTourWithJS/WorldTour/Models/Booking.cs
namespace WorldTour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Booking")]
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            Tickets = new HashSet<Tickets>();
        }

        public int BookingID { get; set; }

        public int FlightID { get; set; }

        [Column("Total Price")]
        public decimal Total_Price { get; set; }

        public int Quantity { get; set; }

        [Required]
        public string BookingName { get; set; }

        [Required]
        public string Email { get; set; }

        public string Phone { get; set; }

        public int? ReturnFlightID { get; set; }

        [Required]
        [StringLength(50)]
        public string Class { get; set; }

        public virtual Flights Flights { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}

WorldTourWithJS/WorldTour/Models/CheckoutViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WorldTour.Models
{
    public class CheckoutViewModel : BTViewModel
    {
        [Required]
        [StringLength(60, MinimumLength = 6, ErrorMessage = "Name must be at least 6 characters long.")]
        [RegularExpression(@"^[a-zA-Z\s]*$", ErrorMessage = "Name can only have English letters and spaces.")]
        public string CardHolder { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]{13,19}$", ErrorMessage = "Card number must have a minimum of 13 numbers and a maximum of 19 numbers, spaces are not allowed.")]
        public string CardNumber { get; set; }

        [Required]
        [RegularExpression(@"^[0-9]{3,4}$", ErrorMessage = "CVV consists of 3 or 4 numbers.")]
        public int CVV { get; set; }

        public string errmessage { get; set; }

    }
}

WorldTourWithJS/WorldTour/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using WorldTour.Models;

namespace WorldTour.Controllers
{
    public class BookingsController : Controller
    {
        private WorldTourContext db = new WorldTourContext();


        //Here we are going to get input from the user
        //about the details of the passengers

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout(BTViewModel t)
        {
            if (!ModelState.IsValid)
            {
                return View("~/Views/Ticket/GetBookingDetails.cshtml", t);
            }
            else
            {
                var t2 = new CheckoutViewModel()
                {
                    BookingName = t.BookingName,
                    Children = t.Children,
                    Class = t.Class,
                    Email = t.Email,
                    FID = t.FID,
                    RFID = t.RFID,
                    Phone = t.Phone,
                    Quantity = t.Quantity,
                    Tickets = t.Tickets,
                    Total_Price = t.Total_Price
                };

                Flights retf;
                Flights depf = db.Flights.Where(x => x.FlightID == t.FID).FirstOrDefault();
                if (t.RFID != null)
                {
                    retf = db.Flights.Where(x => x.FlightID == t.RFID).FirstOrDefault();
                    ViewBag.RetFlight = retf;
                }

                ViewBag.DepFlight = depf;

                return View(t2);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Completion(CheckoutViewModel CVM, string CardType)
        {

            if (!ModelState.IsValid)
            {

                Flights retf;
                Flights depf = db.Flights.Where(x => x.FlightID == CVM.FID).FirstOrDefault();
                if (CVM.RFID != null)
                {
                    retf = db.Flights.Where(x => x.FlightID == CVM.RFID).FirstOrDefault();
                    ViewBag.RetFlight = retf;
                }

                ViewBag.DepFlight = depf;

                return View("~/Views/Bookings/Checkout.cshtml", CVM);
            }
            else
            {
                string passengers = "";
                string DepFlight = "";
                string RetFlight = "";
                Flights depf, retf;
                //Checks if phone is null and formats string accordingly
                if (CVM.Phone == null) CVM.Phone = "You have not given a phone number.";

                //Formats the passenger information text properly

                for (int i = 0; i < CVM.Quantity; i++)
                {
                    passengers += $"<li>Passenger Name: {CVM.Tickets[i].FirstName} {CVM.Tickets[i].LastName} (Adult)\n";
                }
                for (int i = CVM.Quantity; i < CVM.Children; i++)
                {
                    passengers += $"<li>Passenger Name: {CVM.Tickets[i].FirstName} {CVM.Tickets[i].LastName} (Child)\n";
                }

                //Formatting the flight information text
                depf = db.Flights.Where(x => x.FlightID == CVM.FID).FirstOrDefault();
                DepFlight = $@"<h3>Flight Details</h3>
                <ul>
                <li>Flight Number: {depf.FlightID}</li>
                <li>Departure Airport: {depf.Departure_Airport}</li>
                <li>Departure Date & Time: {depf.Departure_Date.ToString()}</li>
                <li>Arrival Airport: {depf.Arrival_Airport}</li>
                <li>Arrival Date & Time: {depf.Arrival_Date.ToString()}</li>
                <li>Company: {depf.Company_Name}</li>
                </ul>";

                //Formats the return flight information text properly
                if (CVM.RFID == null)
                {
                    retf = null;
                    RetFlight = "You have not booked a return flight.";
                }
                else
                {
                    retf = db.Flights.Where(x => x.FlightID == CVM.RFID).FirstOrDefault();

                    RetFlight = $@"<h3>Return Flight Details:</h3>
                    <ul>
                    <li>Flight Number: {retf.FlightID}</li>
                    <li>Departure Airport: {retf.Departure_Airport}</li>
                    <li>Departure Date & Time: {retf.Departure_Date.ToString()}</li>
                    <li>Arrival Airport: {retf.Arrival_Airport}</li>
                    <li>Arrival Date & Time: {retf.Arrival_Date.ToString()}</li>
                    <li>Company: {retf.Company_Name}</li>
                    </ul>";
                }

                var message = $@"Dear {CVM.BookingName},<br />
                You have made the following booking with World Tour: <br />
                <h3>Booking Details:</h3>
                <ul>
                <li>Name: {CVM.BookingName}</li>
                <li>E-mail: {CVM.Email}</li>
                <li> Phone: {CVM.Phone}</li>
                <li>Tickets Booked: {CVM.Quantity + CVM.Children}</li>
                <li>Ticket Class: {CVM.Class}</li>
                <li>Total Cost: {Math.Round(CVM.Total_Price, 2)} &euro;</li>
                </ul>
                <h3>Passenger Details:</h3>
                <ul>
                {passengers}
                </ul>
                {DepFlight}
                {RetFlight}
                <p>Purchase completed with {CardType} credit card ending with {CVM.CardNumber.Substring(CVM.CardNumber.Length - 4) }.</p>";

                var mail = new MailMessage();
                mail.To.Add(CVM.Email);
                mail.Subject = "Booking confirmation from World Travel.";
                mail.Body = message;
                mail.IsBodyHtml = true;

                

                using (db)
                {
                    foreach (var ticket in CVM.Tickets)
                    {
                        db.Tickets.Add(ticket);
                    }

                    Booking book = new Booking
                    {
                        BookingName = CVM.BookingName,
                        Class = CVM.Class,
                        Email = CVM.Email,
                        FlightID = CVM.FID,
                        ReturnFlightID = CVM.RFID,
                        Phone = CVM.Phone,
                        Quantity = CVM.Quantity + CVM.Children,
                        Total_Price = CVM.Total_Price
                    };
                    db.Booking.Add(book);

                    db.Entry(depf).State = EntityState.Detached;
                    depf.Available_Seats -= book.Quantity;
                    db.Entry(depf).State = EntityState.Modified;

                    if (retf != null)
                    {
                        db.Entry(retf).State = EntityState.Detached;
                        retf.Available_Seats -= book.Quantity;
                        db.Entry(retf).State = EntityState.Modified;
                    }
                    db.SaveChanges();
                }

                using (var smtp = new SmtpClient())
                {
                    try
                    {
                        smtp.Send(mail);
                    }
                    catch (Exception)
                    {
                        CVM.errmessage = "There was a problem with our e-mail service. Your booking has been succesfully completed.";
                        return View(CVM);
                    }
                }

                return View(CVM);
            }
        }

    }
}

WorldTourWithJS/WorldTour/Views/Bookings/Checkout.cshtml
@model WorldTour.Models.CheckoutViewModel

@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
    WorldTour.Models.Flights retflight = null;
    var depflight = ViewBag.DepFlight as WorldTour.Models.Flights;
    if (ViewBag.RetFlight != null)
    {
        retflight = ViewBag.RetFlight as WorldTour.Models.Flights;
    }
}

<h2><u>Checkout</u></h2>

<section class="col-md-7 col-xs-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Booking Details:</h3>
        </div>
        <ul>
            <li>Name: @Model.BookingName</li>
            <li>E-mail: @Model.Email</li>
            @if (Model.Phone != null)
            {
                <li>Phone: @Model.Phone</li>
            }
            <li>Tickets Booked: @(Model.Quantity + Model.Children)</li>
            <li class="info">Ticket Class: <span>@Model.Class</span></li>
            <li class="info">Total Cost: <span>@Math.Round(Model.Total_Price, 2) &euro;</span></li>
        </ul>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Passenger Details:</h3>
        </div>
        <ul>
            @for (int i = 0; i < Model.Quantity; i++)
            {
                <li>Passenger Name: @(Model.Tickets[i].FirstName + " " + Model.Tickets[i].LastName) (Adult)</li>
            }
            @for (int i = Model.Quantity; i < Model.Quantity + Model.Children; i++)
            {
                <li>Passenger Name: @(Model.Tickets[i].FirstName + " " + Model.Tickets[i].LastName) (Child)</li>
            }
        </ul>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Flight Details:</h3>
        </div>
        <ul>
            <li>Flight Number: @depflight.FlightID</li>
            <li>Departure Airport: @depflight.Departure_Airport</li>
            <li>Departure Date & Time: @depflight.Departure_Date</li>
            <li>Arrival Airport: @depflight.Arrival_Airport</li>
            <li>Arrival Date & Time: @depflight.Arrival_Date</li>
            <li>Company: @depflight.Company_Name</li>
        </ul>
    </div>
    @if (retflight != null)
            {
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Return Flight Details:</h3>
            </div>
                <ul>
                    <li>Flight Number: @retflight.FlightID</li>
                    <li>Departure Airport: @retflight.Departure_Airport</li>
                    <li>Departure Date & Time: @retflight.Departure_Date</li>
                    <li>Arrival Airport: @retflight.Arrival_Airport</li>
                    <li>Arrival Date & Time: @retflight.Arrival_Date</li>
                    <li>Company: @retflight.Company_Name</li>
                </ul>
            </div>
                }
    </section>



<section class="col-md-5 col-xs-12">
    @using (Html.BeginForm("Completion", "Bookings"))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "Please enter all of your details correctly!", new { @class = "alert-danger" })

        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title"> Credit Card Information</h3>
            </div>
                    <label class="card">Card Type:</label>
                    <select name="CardType">
                        <option value="American Express">American Express</option>
                        <option value="Diners">Diners</option>
                        <option value="Maestro">Maestro</option>
                        <option value="Mastercard">Mastercard</option>
                        <option value="Visa">Visa</option>
                    </select><br />
                    <label class="card">Card Holder:</label>
                    @Html.TextBoxFor(m => m.CardHolder, new { required = "required" })<br />
                    @Html.ValidationMessageFor(model => model.CardHolder, "", new { @class = "alert-danger" })<br />
                    <label class="card">Card Number:</label>
                    @Html.TextBoxFor(m => m.CardNumber, new { required = "required" })<br />
                    @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "alert-danger" })<br />
                    <label class="card">Expiration Date:</label>
                    <select>
                        <option value="Jan">01</option>
                        <option value="Feb">02</option>
                        <option value="Mar">03</option>
                        <option value="Apr">04</option>
                        <option value="May">05</option>
                        <option value="Jun">06</option>
                        <option value="Jul">07</option>
                        <option value="Aug">08</option>
                        <option value="Sep">09</option>
                        <option value="Oct">10</option>
                        <option value="Nov">11</option>
                        <option value="Dec">12</option>
                    </select>
                    <select>
                        <option value="17">2017</option>
                        <option value="18">2018</option>
                        <option value="19">2019</option>
                        <option value="20">2020</option>
                        <option value="21">2021</option>
                        <option value="22">2022</option>
                        <option value="23">2023</option>
                        <option value="24">2024</option>
                        <option value="25">2025</option>
                        <option value="26">2026</option>
                    </select><br />
                    <label class="card">CVV:</label>
                    @Html.TextBoxFor(m => m.CVV, new { required = "required", maxlength = "4" })<br />
                    @Html.ValidationMessageFor(model => model.CVV, "", new { @class = "alert-danger" })<br />
            </div>

                    @Html.HiddenFor(m => m.BookingName)
                    @Html.HiddenFor(m => m.Email)
                    @Html.HiddenFor(m => m.Children)
                    @Html.HiddenFor(m => m.Class)
                    @Html.HiddenFor(m => m.FID)
                    @Html.HiddenFor(m => m.Phone)
                    @Html.HiddenFor(m => m.Total_Price)
                    @Html.HiddenFor(m => m.RFID)
                    @Html.HiddenFor(m => m.Quantity)

        for (int i = 0; i < (Model.Quantity + Model.Children); i++)
        {
            @Html.HiddenFor(m => m.Tickets[i].FirstName);
            @Html.HiddenFor(m => m.Tickets[i].LastName);
        }

        <input type="submit" value="Submit" class="btn btn-success" id="submit"/>
    }
</section>

<script src="~/scripts/waitingfor.js"></script>
<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            waitingDialog.show("Please wait, your booking is almost done!");
            setTimeout(function () {
                waitingDialog.hide();
            }, 5000);
        });
    });
</script>

WorldTourWithJS/WorldTour/Views/Bookings/Completion.cshtml
@model WorldTour.Models.CheckoutViewModel
@{
    ViewBag.Title = "Completion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="confirmation">
<div class="panel panel-primary">
    <div class="panel-heading">
        <h2 class="panel-title"> Completion</h2>
    </div>
            <p>Your purchase has been successfully completed. An email with the booking information will be sent to you soon.</p>
    </div>
            <br />

            @{
                if (Model.errmessage != "")
                {
                    <p style="color:red; font-weight:700;">@Model.errmessage</p>
                }
            }

            <a href="@Url.Action("Index", "Home")">Return to our homepage.</a>
    <img src="~/Content/Plane.png" id="plane" width="9%"/>
</div>

<script>
    $(document).ready(function () {
        $("#plane").animate({
            left: "+=87%",
            top: "-=15%"
            }, 10000, "swing",function () {
                $("#plane").fadeOut("fast");
            });
    });
</script>